---
downloads: ~/.ansible-downloads/

homebrew_use_brewfile: false

homebrew_taps:
  - homebrew/cask-fonts
  - homebrew/cask-versions

homebrew_installed_packages:
  # essential
  - vim
  - zsh
  - mackup
  - wget
  - openssh
  - openssl
  - xz
  - zlib
  # https://github.com/ibraheemdev/modern-unix
  - bat
  - tealdeer
  # old fashioned
  - coreutils
  - moreutils
  - findutils
  - gnutls
  - gnupg
  # development
  - git
  - git-extras
  - tig
  - scmpuff
  - nvm
  - rust
  # misc
  - youtube-dl
  - mas
  # current job
  - zopfli
  - teleport
  - awscli

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  # fonts
  - font-fira-code
  - font-jetbrains-mono
  # quicklook addons
  - quicklook-json
  - qlmarkdown
  - quicklook-csv
  - qlimagesize
  # browsers
  - brave-browser
  - google-chrome
  - firefox
  - microsoft-edge
  # essential
  - appcleaner
  - 1password7
  - yandex-disk
  # tools
  - raycast
  - quitter
  - rescuetime
  - bartender
  - cleanshot
  - raindropio
  - paragon-ntfs
  # misc
  - airbuddy
  - transmission
  - qflipper
  - logitech-g-hub
  - calibre
  # development
  - iterm2
  - visual-studio-code
  - podman
  - proxyman
  # communication
  - zoom
  - discord
  # media
  - spotify
  - vlc
  # current job
  - pritunl
  - figma

mas_signin_dialog: false
mas_upgrade_all_apps: true
mas_installed_apps:
  - { id: 1607635845, name: "Velja" }
  - { id: 425424353, name: "The Unarchiver" }
  - { id: 967805235, name: "Paste" }
  - { id: 1365531024, name: "1Blocker" }
  - { id: 409183694, name: "Keynote" }
  - { id: 409203825, name: "Numbers" }
  - { id: 409201541, name: "Pages" }
  - { id: 1569600264, name: "Pandan" }
  - { id: 1529448980, name: "Reeder" }
  - { id: 803453959, name: "Slack" }
  - { id: 897118787, name: "Shazam" }
  - { id: 500154009, name: "Bitdefender Virus Scanner" }
  - { id: 1470584107, name: "Dato" }
  - { id: 639968404, name: "Parcel" }
  - { id: 1263070803, name: "Lungo" }
  - { id: 1356178125, name: "Outline" }
mas_uninstalled_apps:
  - { id: 408981434, name: "iMovie" }
  - { id: 682658836, name: "GarageBand" }

configure_macos: true
macos_script: "bash .macos --no-restart && bash .apps --no-restart"

configure_dock: true
dockitems_remove:
  - TV
  - Music
  - Messages
  - Facetime
  - Numbers
  - Pages
  - Keynote
  - Books
  - App Store
  - Maps
  - Contacts
  - Notes

# Install packages from other package managers.
npm_packages: []
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

touch_id_sudo_line: "auth       sufficient     pam_tid.so"
