---
- hosts: all

  vars_files:
    - default.config.yml

  roles:
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['mas']

  tasks:
    - import_tasks: tasks/macos.yml
      when: configure_macos
      tags: ['macos']

    - import_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']
