code --install-extension DavidAnson.vscode-markdownlint
code --install-extension EditorConfig.EditorConfig
code --install-extension Orta.vscode-jest
code --install-extension PeterJausovec.vscode-docker
code --install-extension WallabyJs.quokka-vscode
code --install-extension christian-kohler.path-intellisense
code --install-extension dbaeumer.vscode-eslint
code --install-extension dzannotti.vscode-babel-coloring
code --install-extension eg2.tslint
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension file-icons.file-icons
code --install-extension mohsen1.prettify-json
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension robinbentley.sass-indented
code --install-extension shinnn.stylelint
code --install-extension tonsky.theme-alabaster
code --install-extension viatsko.theme-base16-ocean-dark
code --install-extension waderyan.babelrc
code --install-extension waderyan.gitblame
code --install-extension wengerk.highlight-bad-chars
code --install-extension wix.vscode-import-cost
code --install-extension xabikos.ReactSnippets