ext install DavidAnson.vscode-markdownlint
ext install EditorConfig.EditorConfig
ext install Orta.vscode-jest
ext install PeterJausovec.vscode-docker
ext install WallabyJs.quokka-vscode
ext install christian-kohler.path-intellisense
ext install dbaeumer.vscode-eslint
ext install dzannotti.vscode-babel-coloring
ext install eg2.tslint
ext install eg2.vscode-npm-script
ext install esbenp.prettier-vscode
ext install file-icons.file-icons
ext install mohsen1.prettify-json
ext install msjsdiag.debugger-for-chrome
ext install robinbentley.sass-indented
ext install shinnn.stylelint
ext install viatsko.theme-base16-ocean-dark
ext install waderyan.babelrc
ext install waderyan.gitblame
ext install wengerk.highlight-bad-chars
ext install wix.vscode-import-cost
ext install xabikos.ReactSnippets
