#!/bin/bash

set -eu

cd "$HOME"

source "$HOME"/.xdg.dirs
source "$XDG_CONFIG_HOME"/shell/xdg

# Specify permissions.
chmod 700 "$XDG_CONFIG_HOME"

if [[ "$OSTYPE" == "darwin"* ]]; then
  # Run brew bundle.
  /opt/homebrew/bin/brew bundle
  echo "brew dependencies installation is complete."

  # Apply all defaults.
  find "$XDG_CONFIG_HOME" -type f -name "defaults" | while read -r file; do
    # Check if the file is executable and execute it
    if [ -x "$file" ]; then
      # Execute the file
      /bin/bash -c "$file --no-restart"
    fi
  done
  echo "defaults applying is complete."

  # Restore all mackup settings.
  /opt/homebrew/bin/mackup restore && /opt/homebrew/bin/mackup uninstall
  echo "mackup settings restoring is complete."

  # Specify docker-buildx dir
  mkdir -p "$DOCKER_CONFIG/cli-plugins"
  ln -sfn "$HOMEBREW_PREFIX/opt/docker-buildx/bin/docker-buildx" "$DOCKER_CONFIG/cli-plugins/docker-buildx"
  echo "docker-buildx specified."

  # Install old-fashioned apps.
  TYPOGRAPHY="3.9"
  CHROMIUM_GOST="133.0.6943.53"
  AMNEZIA="4.8.2.3"

  cd "$XDG_DOWNLOAD_DIR"
  [ ! -f "ilya-birman-typolayout-$TYPOGRAPHY-mac.dmg" ] && curl -fLo "ilya-birman-typolayout-$TYPOGRAPHY-mac.dmg" "https://ilyabirman.ru/typography-layout/download/ilya-birman-typolayout-$TYPOGRAPHY-mac.dmg"
  [ ! -f "$CHROMIUM_GOST-macos-arm64.tar.bz2" ] && curl -fLo "$CHROMIUM_GOST-macos-arm64.tar.bz2" "https://github.com/deemru/Chromium-Gost/releases/download/$CHROMIUM_GOST/chromium-gost-$CHROMIUM_GOST-macos-arm64.tar.bz2"
  [ ! -f "AmneziaVPN_$AMNEZIA.dmg" ] && curl -fLo "AmneziaVPN_$AMNEZIA.dmg" "https://github.com/amnezia-vpn/amnezia-client/releases/download/${AMNEZIA%.*}/AmneziaVPN_$AMNEZIA.dmg"
  [ ! -f "Yandex.Disk.dmg" ] && curl -fLo "Yandex.Disk.dmg" "https://disk.yandex.ru/download/Yandex.Disk.dmg/?instant=1"
  cd "$HOME"
  echo "Downloading is complete."

  # Specify sparse-checkout.
  /opt/homebrew/bin/yadm sparse-checkout init
  /opt/homebrew/bin/yadm sparse-checkout set --no-cone '/*' '!README.md' '!LICENSE' '!.editoconfig'
fi
