---
- name: Run .macos dotfiles.
  command: "{{ macos_script }}"
  changed_when: false

- name: Ensure TouchId is available.
  shell: set -o pipefail && bioutil -rs |  grep functionality | awk '{print $4}'
  changed_when: false
  register: touch_id_status

- name: Ensure that TouchId is installed as authentication method for sudo.
  command: cat /etc/pam.d/sudo
  register: touch_id_enabled_for_root
  changed_when: false
  when: touch_id_status.stdout == "1"
  
- name: Install TouchId as authentication method for sudo.
  lineinfile:
    path: /etc/pam.d/sudo
    line: "{{ touch_id_sudo_line }}"
    insertbefore: "auth       sufficient     pam_smartcard.so"
  become: true
  when: touch_id_sudo_line not in touch_id_enabled_for_root.stdout
