#!/bin/sh

# Easier navigation:
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

# Always enable colored `grep` output
# Note: `GREP_OPTIONS="--color=auto"` is deprecated, hence the alias usage.
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# Shortcuts
alias ll="ls -laG"
alias disk="cd $HOME/Yandex.Disk-andreychev.ru.localized"
alias icloud="cd $HOME/Library/Mobile\ Documents/com~apple~CloudDocs"

alias o="open"
alias oo="open ."
alias e="code"

# All stupidity
alias :q="exit"
alias claer="clear"

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en0"
alias ips="ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"

# Canonical hex dump; some systems have this symlinked
command -v hd >/dev/null || alias hd="hexdump -C"

# macOS has no `md5sum`, so use `md5` as a fallback
command -v md5sum >/dev/null || alias md5sum="md5"

# macOS has no `sha1sum`, so use `shasum` as a fallback
command -v sha1sum >/dev/null || alias sha1sum="shasum"

# Open all the dotfiles in VSCode
alias dotfiles='for _path in $(yadm list); do code - "$_path"; done; unset _path'

alias macosup="sudo softwareupdate -i -a"
alias brewup="brew update && brew upgrade && brew cleanup"

# Default application aliases
alias vscode="code"
alias chrome="open -na 'Google Chrome' --args '--user-data-dir=$XDG_STATE_HOME/.temp-chrome-profile' --ignore-certificate-errors"
alias firefox="open -na 'Firefox'"

# Kill all the tabs in Chrome to free up memory
# [C] explained: http://www.commandlinefu.com/commands/view/402/exclude-grep-from-your-grepped-output-of-ps-alias-included-in-description
alias chromekill="ps ux | grep '[C]hrome Helper --type=renderer' | grep -v extension-process | tr -s ' ' | cut -d ' ' -f2 | xargs kill"

