#!/bin/bash

# Easier navigation:
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

# Enable aliases to be sudo'ed
alias sudo="sudo "

# Always enable colored `grep` output
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# Shortcuts for file operations
alias exa='eza'
alias k='exa --color -la --git'
alias o="open"
alias oo="open ."

# Git aliases
alias gs="scmpuff_status"
alias ga="git add"

# Navigation to specific directories
alias disk='cd "$HOME"/Yandex.Disk.localized'
alias icloud='cd "$HOME"/Library/Mobile\ Documents/com~apple~CloudDocs'

# Miscellaneous aliases
alias :q="exit"     # Exit command
alias claer="clear" # Clear the terminal

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en0"
alias ips="ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"

# Canonical hex dump; some systems have this symlinked
command -v hd >/dev/null || alias hd="hexdump -C"

# Fallback for md5sum and sha1sum on macOS
command -v md5sum >/dev/null || alias md5sum="md5"
command -v sha1sum >/dev/null || alias sha1sum="shasum"

# Open all the dotfiles in editor
alias dotfiles='e - $(yadm list)'

# System update aliases
alias macosup="sudo softwareupdate -i -a"
alias brewup="brew update && brew upgrade && brew cleanup"
alias zshup='zsh "$ANTIDOTE_HOME"/mattmc3/antidote/antidote update'
alias nvimup='nvim --headless "+Lazy! sync" +qa'

# Default application aliases
alias chrome="open -na 'Google Chrome' --args --ignore-certificate-errors"
alias firefox="open -na 'Firefox'"

# Kill all the tabs in Chrome to free up memory
alias chromekill="ps ux | grep '[C]hrome Helper --type=renderer' | grep -v extension-process | tr -s ' ' | cut -d ' ' -f2 | xargs kill"

alias rn-photos="exifrename -f '{year}{month}{day}_{hour}{minute}{second}_{fstop}_{focal_length_35}'"
