[env]
NODE_OPTIONS="--max_old_space_size=1536"

[tools]
go = "1.26.1"
node = "22.14.0"
python = "3.11.11"
uv = "latest"
"npm:yarn" = "1.22.22"
"npm:npm" = "latest"
"npm:pnpm" = "10.33.0"
"npm:sql-formatter" = "latest"
rust = "stable"

[settings]
idiomatic_version_file_enable_tools = ["node"]
